# Generated by Django 2.0.5 on 2018-06-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180615_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='userpic/default.jpg', upload_to='userpic'),
        ),
    ]
